/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'InTransit' : IDL.Null,
  'Delivered' : IDL.Null,
  'PickedUp' : IDL.Null,
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Success' : IDL.Null,
  'Processing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'VodafoneCash' : IDL.Null,
  'InstaPay' : IDL.Null,
  'BankVisa' : IDL.Null,
  'CashOnDelivery' : IDL.Null,
});
export const UserId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'itemDescription' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pickupAddress' : IDL.Text,
  'dropoffAddress' : IDL.Text,
  'paymentId' : IDL.Opt(IDL.Nat),
  'courierId' : IDL.Opt(IDL.Nat),
});
export const AssignOrderResult = IDL.Variant({
  'ok' : Order,
  'err' : IDL.Text,
  'alreadyAssigned' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const CompanyInput = IDL.Record({
  'nameAr' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Text,
});
export const CompanyId = IDL.Nat;
export const CompanyPublic = IDL.Record({
  'id' : CompanyId,
  'nameAr' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Text,
});
export const OfferInput = IDL.Record({
  'title' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'discount' : IDL.Float64,
  'titleAr' : IDL.Text,
  'validUntil' : Timestamp,
});
export const OfferId = IDL.Nat;
export const OfferPublic = IDL.Record({
  'id' : OfferId,
  'title' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'discount' : IDL.Float64,
  'titleAr' : IDL.Text,
  'validUntil' : Timestamp,
});
export const ProductInput = IDL.Record({
  'nameAr' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'companyId' : CompanyId,
});
export const ProductId = IDL.Nat;
export const ProductPublic = IDL.Record({
  'id' : ProductId,
  'nameAr' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'companyId' : CompanyId,
});
export const BroadcastSegment = IDL.Variant({
  'All' : IDL.Null,
  'PendingOrders' : IDL.Null,
  'ActiveUsers' : IDL.Null,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'itemDescription' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pickupAddress' : IDL.Text,
  'dropoffAddress' : IDL.Text,
  'paymentId' : IDL.Opt(IDL.Nat),
  'courierId' : IDL.Opt(IDL.Nat),
});
export const CourierPublic = IDL.Record({
  'id' : IDL.Nat,
  'vehicleType' : IDL.Text,
  'userId' : UserId,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'isAvailable' : IDL.Bool,
  'isActive' : IDL.Bool,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'totalDeliveries' : IDL.Nat,
});
export const CourierLoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'courier' : CourierPublic }),
  'wrongCredentials' : IDL.Null,
  'inactive' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'OrderCancelled' : IDL.Null,
  'CourierArrived' : IDL.Null,
  'PaymentFailed' : IDL.Null,
  'PaymentProcessed' : IDL.Null,
  'OrderCreated' : IDL.Null,
  'OrderInTransit' : IDL.Null,
  'OrderAccepted' : IDL.Null,
  'OrderDelivered' : IDL.Null,
});
export const CreateOrderRequest = IDL.Record({
  'itemDescription' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : IDL.Float64,
  'pickupAddress' : IDL.Text,
  'dropoffAddress' : IDL.Text,
});
export const PaymentMethodSettingPublic = IDL.Record({
  'method' : PaymentMethod,
  'isEnabled' : IDL.Bool,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CourierStats = IDL.Record({
  'earningsThisMonth' : IDL.Float64,
  'completedThisMonth' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'totalEarnings' : IDL.Float64,
  'totalDeliveries' : IDL.Nat,
});
export const StatusCount = IDL.Record({
  'status' : OrderStatus,
  'count' : IDL.Nat,
});
export const DailyOrderCount = IDL.Record({
  'date' : IDL.Text,
  'count' : IDL.Nat,
});
export const PaymentMethodCount = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'count' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'ordersByStatus' : IDL.Vec(StatusCount),
  'totalOrders' : IDL.Nat,
  'ordersLast7Days' : IDL.Vec(DailyOrderCount),
  'totalUsers' : IDL.Nat,
  'ordersByPaymentMethod' : IDL.Vec(PaymentMethodCount),
});
export const NotificationPublic = IDL.Record({
  'id' : IDL.Nat,
  'messageAr' : IDL.Text,
  'notifType' : NotificationType,
  'userId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PaymentPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'errorMessage' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : UserPublic }),
  'err' : IDL.Text,
});
export const RegisterRequest = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderSearchFilter = IDL.Record({
  'status' : IDL.Opt(OrderStatus),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  'acceptOrder' : IDL.Func([IDL.Text, IDL.Nat], [AssignOrderResult], []),
  'adminCreateCompany' : IDL.Func(
      [IDL.Text, CompanyInput],
      [IDL.Variant({ 'ok' : CompanyPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateOffer' : IDL.Func(
      [IDL.Text, OfferInput],
      [IDL.Variant({ 'ok' : OfferPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateProduct' : IDL.Func(
      [IDL.Text, ProductInput],
      [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteCompany' : IDL.Func(
      [IDL.Text, CompanyId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteOffer' : IDL.Func(
      [IDL.Text, OfferId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteProduct' : IDL.Func(
      [IDL.Text, ProductId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminLoginCall' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSendBroadcastNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BroadcastSegment],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminSetPaymentMethodEnabled' : IDL.Func(
      [IDL.Text, PaymentMethod, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateCompany' : IDL.Func(
      [IDL.Text, CompanyId, CompanyInput],
      [IDL.Variant({ 'ok' : CompanyPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateOffer' : IDL.Func(
      [IDL.Text, OfferId, OfferInput],
      [IDL.Variant({ 'ok' : OfferPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateProduct' : IDL.Func(
      [IDL.Text, ProductId, ProductInput],
      [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
      [],
    ),
  'cancelOrder' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
      [],
    ),
  'confirmDelivery' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmPickup' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'courierLogin' : IDL.Func([IDL.Text, IDL.Text], [CourierLoginResult], []),
  'createNotification' : IDL.Func(
      [IDL.Nat, NotificationType, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
      [],
      ['oneway'],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, CreateOrderRequest],
      [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
      [],
    ),
  'getActiveCompanies' : IDL.Func([], [IDL.Vec(CompanyPublic)], ['query']),
  'getActiveOffers' : IDL.Func([], [IDL.Vec(OfferPublic)], ['query']),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getAllOrdersAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAllPaymentMethodSettings' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethodSettingPublic)],
      ['query'],
    ),
  'getAllUsersAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCompany' : IDL.Func([CompanyId], [IDL.Opt(CompanyPublic)], ['query']),
  'getCourierLocation' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'lat' : IDL.Float64,
            'lng' : IDL.Float64,
            'orderId' : IDL.Nat,
            'timestamp' : IDL.Int,
            'courierId' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getCourierProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CourierPublic)],
      ['query'],
    ),
  'getCourierStats' : IDL.Func([IDL.Text], [CourierStats], ['query']),
  'getDashboardStats' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DashboardStats, 'err' : IDL.Text })],
      ['query'],
    ),
  'getEnabledPaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'getMyCourierOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NotificationPublic)],
      ['query'],
    ),
  'getMyOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'getOffer' : IDL.Func([OfferId], [IDL.Opt(OfferPublic)], ['query']),
  'getOrder' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(OrderPublic)], ['query']),
  'getOrderPayments' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(PaymentPublic)],
      ['query'],
    ),
  'getOrdersByPaymentMethodAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PaymentMethodCount), 'err' : IDL.Text })],
      ['query'],
    ),
  'getOrdersByStatusAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(StatusCount), 'err' : IDL.Text })],
      ['query'],
    ),
  'getOrdersLast7DaysAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DailyOrderCount), 'err' : IDL.Text })],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(PaymentPublic)],
      ['query'],
    ),
  'getPendingOrdersForCourier' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
  'getTotalOrdersAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getTotalUsersAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserByIdAdmin' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Opt(UserPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'initiatePayment' : IDL.Func(
      [IDL.Text, IDL.Nat, PaymentMethod, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PaymentPublic, 'err' : IDL.Text })],
      [],
    ),
  'isAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listCompanies' : IDL.Func([IDL.Bool], [IDL.Vec(CompanyPublic)], ['query']),
  'listOffers' : IDL.Func([IDL.Bool], [IDL.Vec(OfferPublic)], ['query']),
  'listProducts' : IDL.Func([IDL.Bool], [IDL.Vec(ProductPublic)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'markAllNotificationsRead' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationRead' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'register' : IDL.Func(
      [RegisterRequest],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'registerCourier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CourierPublic, 'err' : IDL.Text })],
      [],
    ),
  'searchOrders' : IDL.Func(
      [IDL.Text, OrderSearchFilter],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'searchUsersAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'setUserActiveAdmin' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateCourierLocation' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, OrderStatus],
      [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'InTransit' : IDL.Null,
    'Delivered' : IDL.Null,
    'PickedUp' : IDL.Null,
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Success' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'VodafoneCash' : IDL.Null,
    'InstaPay' : IDL.Null,
    'BankVisa' : IDL.Null,
    'CashOnDelivery' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'itemDescription' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'estimatedPrice' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'pickupAddress' : IDL.Text,
    'dropoffAddress' : IDL.Text,
    'paymentId' : IDL.Opt(IDL.Nat),
    'courierId' : IDL.Opt(IDL.Nat),
  });
  const AssignOrderResult = IDL.Variant({
    'ok' : Order,
    'err' : IDL.Text,
    'alreadyAssigned' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const CompanyInput = IDL.Record({
    'nameAr' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Text,
  });
  const CompanyId = IDL.Nat;
  const CompanyPublic = IDL.Record({
    'id' : CompanyId,
    'nameAr' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Text,
  });
  const OfferInput = IDL.Record({
    'title' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'discount' : IDL.Float64,
    'titleAr' : IDL.Text,
    'validUntil' : Timestamp,
  });
  const OfferId = IDL.Nat;
  const OfferPublic = IDL.Record({
    'id' : OfferId,
    'title' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'discount' : IDL.Float64,
    'titleAr' : IDL.Text,
    'validUntil' : Timestamp,
  });
  const ProductInput = IDL.Record({
    'nameAr' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'companyId' : CompanyId,
  });
  const ProductId = IDL.Nat;
  const ProductPublic = IDL.Record({
    'id' : ProductId,
    'nameAr' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'companyId' : CompanyId,
  });
  const BroadcastSegment = IDL.Variant({
    'All' : IDL.Null,
    'PendingOrders' : IDL.Null,
    'ActiveUsers' : IDL.Null,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'itemDescription' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'estimatedPrice' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'pickupAddress' : IDL.Text,
    'dropoffAddress' : IDL.Text,
    'paymentId' : IDL.Opt(IDL.Nat),
    'courierId' : IDL.Opt(IDL.Nat),
  });
  const CourierPublic = IDL.Record({
    'id' : IDL.Nat,
    'vehicleType' : IDL.Text,
    'userId' : UserId,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'isAvailable' : IDL.Bool,
    'isActive' : IDL.Bool,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'totalDeliveries' : IDL.Nat,
  });
  const CourierLoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'courier' : CourierPublic }),
    'wrongCredentials' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'OrderCancelled' : IDL.Null,
    'CourierArrived' : IDL.Null,
    'PaymentFailed' : IDL.Null,
    'PaymentProcessed' : IDL.Null,
    'OrderCreated' : IDL.Null,
    'OrderInTransit' : IDL.Null,
    'OrderAccepted' : IDL.Null,
    'OrderDelivered' : IDL.Null,
  });
  const CreateOrderRequest = IDL.Record({
    'itemDescription' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'estimatedPrice' : IDL.Float64,
    'pickupAddress' : IDL.Text,
    'dropoffAddress' : IDL.Text,
  });
  const PaymentMethodSettingPublic = IDL.Record({
    'method' : PaymentMethod,
    'isEnabled' : IDL.Bool,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CourierStats = IDL.Record({
    'earningsThisMonth' : IDL.Float64,
    'completedThisMonth' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'totalEarnings' : IDL.Float64,
    'totalDeliveries' : IDL.Nat,
  });
  const StatusCount = IDL.Record({ 'status' : OrderStatus, 'count' : IDL.Nat });
  const DailyOrderCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const PaymentMethodCount = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'count' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'ordersByStatus' : IDL.Vec(StatusCount),
    'totalOrders' : IDL.Nat,
    'ordersLast7Days' : IDL.Vec(DailyOrderCount),
    'totalUsers' : IDL.Nat,
    'ordersByPaymentMethod' : IDL.Vec(PaymentMethodCount),
  });
  const NotificationPublic = IDL.Record({
    'id' : IDL.Nat,
    'messageAr' : IDL.Text,
    'notifType' : NotificationType,
    'userId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PaymentPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'errorMessage' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : UserPublic }),
    'err' : IDL.Text,
  });
  const RegisterRequest = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderSearchFilter = IDL.Record({
    'status' : IDL.Opt(OrderStatus),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    'acceptOrder' : IDL.Func([IDL.Text, IDL.Nat], [AssignOrderResult], []),
    'adminCreateCompany' : IDL.Func(
        [IDL.Text, CompanyInput],
        [IDL.Variant({ 'ok' : CompanyPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateOffer' : IDL.Func(
        [IDL.Text, OfferInput],
        [IDL.Variant({ 'ok' : OfferPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateProduct' : IDL.Func(
        [IDL.Text, ProductInput],
        [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteCompany' : IDL.Func(
        [IDL.Text, CompanyId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteOffer' : IDL.Func(
        [IDL.Text, OfferId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteProduct' : IDL.Func(
        [IDL.Text, ProductId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminLoginCall' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSendBroadcastNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BroadcastSegment],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminSetPaymentMethodEnabled' : IDL.Func(
        [IDL.Text, PaymentMethod, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateCompany' : IDL.Func(
        [IDL.Text, CompanyId, CompanyInput],
        [IDL.Variant({ 'ok' : CompanyPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateOffer' : IDL.Func(
        [IDL.Text, OfferId, OfferInput],
        [IDL.Variant({ 'ok' : OfferPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateProduct' : IDL.Func(
        [IDL.Text, ProductId, ProductInput],
        [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
        [],
      ),
    'cancelOrder' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
        [],
      ),
    'confirmDelivery' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmPickup' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'courierLogin' : IDL.Func([IDL.Text, IDL.Text], [CourierLoginResult], []),
    'createNotification' : IDL.Func(
        [IDL.Nat, NotificationType, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
        [],
        ['oneway'],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, CreateOrderRequest],
        [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
        [],
      ),
    'getActiveCompanies' : IDL.Func([], [IDL.Vec(CompanyPublic)], ['query']),
    'getActiveOffers' : IDL.Func([], [IDL.Vec(OfferPublic)], ['query']),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getAllOrdersAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAllPaymentMethodSettings' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethodSettingPublic)],
        ['query'],
      ),
    'getAllUsersAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCompany' : IDL.Func([CompanyId], [IDL.Opt(CompanyPublic)], ['query']),
    'getCourierLocation' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'lat' : IDL.Float64,
              'lng' : IDL.Float64,
              'orderId' : IDL.Nat,
              'timestamp' : IDL.Int,
              'courierId' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getCourierProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CourierPublic)],
        ['query'],
      ),
    'getCourierStats' : IDL.Func([IDL.Text], [CourierStats], ['query']),
    'getDashboardStats' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DashboardStats, 'err' : IDL.Text })],
        ['query'],
      ),
    'getEnabledPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getMyCourierOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'getOffer' : IDL.Func([OfferId], [IDL.Opt(OfferPublic)], ['query']),
    'getOrder' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(OrderPublic)],
        ['query'],
      ),
    'getOrderPayments' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(PaymentPublic)],
        ['query'],
      ),
    'getOrdersByPaymentMethodAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PaymentMethodCount), 'err' : IDL.Text })],
        ['query'],
      ),
    'getOrdersByStatusAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(StatusCount), 'err' : IDL.Text })],
        ['query'],
      ),
    'getOrdersLast7DaysAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(DailyOrderCount), 'err' : IDL.Text })],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(PaymentPublic)],
        ['query'],
      ),
    'getPendingOrdersForCourier' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
    'getTotalOrdersAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getTotalUsersAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserByIdAdmin' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Opt(UserPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'initiatePayment' : IDL.Func(
        [IDL.Text, IDL.Nat, PaymentMethod, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PaymentPublic, 'err' : IDL.Text })],
        [],
      ),
    'isAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listCompanies' : IDL.Func([IDL.Bool], [IDL.Vec(CompanyPublic)], ['query']),
    'listOffers' : IDL.Func([IDL.Bool], [IDL.Vec(OfferPublic)], ['query']),
    'listProducts' : IDL.Func([IDL.Bool], [IDL.Vec(ProductPublic)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'markAllNotificationsRead' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationRead' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'register' : IDL.Func(
        [RegisterRequest],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'registerCourier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CourierPublic, 'err' : IDL.Text })],
        [],
      ),
    'searchOrders' : IDL.Func(
        [IDL.Text, OrderSearchFilter],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'searchUsersAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'setUserActiveAdmin' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateCourierLocation' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, OrderStatus],
        [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };