/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssignOrderResult = { 'ok' : Order } |
  { 'err' : string } |
  { 'alreadyAssigned' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type BroadcastSegment = { 'All' : null } |
  { 'PendingOrders' : null } |
  { 'ActiveUsers' : null };
export type CompanyId = bigint;
export interface CompanyInput {
  'nameAr' : string,
  'descriptionAr' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'logoUrl' : string,
}
export interface CompanyPublic {
  'id' : CompanyId,
  'nameAr' : string,
  'descriptionAr' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'logoUrl' : string,
}
export type CourierLoginResult = {
    'ok' : { 'token' : string, 'courier' : CourierPublic }
  } |
  { 'wrongCredentials' : null } |
  { 'inactive' : null };
export interface CourierPublic {
  'id' : bigint,
  'vehicleType' : string,
  'userId' : UserId,
  'name' : string,
  'joinedAt' : Timestamp,
  'isAvailable' : boolean,
  'isActive' : boolean,
  'rating' : number,
  'phone' : string,
  'totalDeliveries' : bigint,
}
export interface CourierStats {
  'earningsThisMonth' : number,
  'completedThisMonth' : bigint,
  'averageRating' : number,
  'totalEarnings' : number,
  'totalDeliveries' : bigint,
}
export interface CreateOrderRequest {
  'itemDescription' : string,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : number,
  'pickupAddress' : string,
  'dropoffAddress' : string,
}
export interface DailyOrderCount { 'date' : string, 'count' : bigint }
export interface DashboardStats {
  'ordersByStatus' : Array<StatusCount>,
  'totalOrders' : bigint,
  'ordersLast7Days' : Array<DailyOrderCount>,
  'totalUsers' : bigint,
  'ordersByPaymentMethod' : Array<PaymentMethodCount>,
}
export type LoginResult = { 'ok' : { 'token' : string, 'user' : UserPublic } } |
  { 'err' : string };
export interface NotificationPublic {
  'id' : bigint,
  'messageAr' : string,
  'notifType' : NotificationType,
  'userId' : bigint,
  'isRead' : boolean,
  'orderId' : [] | [bigint],
  'message' : string,
  'timestamp' : bigint,
}
export type NotificationType = { 'OrderCancelled' : null } |
  { 'CourierArrived' : null } |
  { 'PaymentFailed' : null } |
  { 'PaymentProcessed' : null } |
  { 'OrderCreated' : null } |
  { 'OrderInTransit' : null } |
  { 'OrderAccepted' : null } |
  { 'OrderDelivered' : null };
export type OfferId = bigint;
export interface OfferInput {
  'title' : string,
  'descriptionAr' : string,
  'description' : string,
  'isActive' : boolean,
  'discount' : number,
  'titleAr' : string,
  'validUntil' : Timestamp,
}
export interface OfferPublic {
  'id' : OfferId,
  'title' : string,
  'descriptionAr' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'discount' : number,
  'titleAr' : string,
  'validUntil' : Timestamp,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'itemDescription' : string,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pickupAddress' : string,
  'dropoffAddress' : string,
  'paymentId' : [] | [bigint],
  'courierId' : [] | [bigint],
}
export type OrderId = bigint;
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'itemDescription' : string,
  'paymentMethod' : PaymentMethod,
  'estimatedPrice' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pickupAddress' : string,
  'dropoffAddress' : string,
  'paymentId' : [] | [bigint],
  'courierId' : [] | [bigint],
}
export interface OrderSearchFilter {
  'status' : [] | [OrderStatus],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
}
export type OrderStatus = { 'InTransit' : null } |
  { 'Delivered' : null } |
  { 'PickedUp' : null } |
  { 'Accepted' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'VodafoneCash' : null } |
  { 'InstaPay' : null } |
  { 'BankVisa' : null } |
  { 'CashOnDelivery' : null };
export interface PaymentMethodCount {
  'paymentMethod' : PaymentMethod,
  'count' : bigint,
}
export interface PaymentMethodSettingPublic {
  'method' : PaymentMethod,
  'isEnabled' : boolean,
}
export interface PaymentPublic {
  'id' : bigint,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'errorMessage' : [] | [string],
  'orderId' : bigint,
  'timestamp' : bigint,
  'phoneNumber' : [] | [string],
  'amount' : number,
  'transactionId' : [] | [string],
}
export type PaymentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Success' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export type ProductId = bigint;
export interface ProductInput {
  'nameAr' : string,
  'descriptionAr' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
  'companyId' : CompanyId,
}
export interface ProductPublic {
  'id' : ProductId,
  'nameAr' : string,
  'descriptionAr' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
  'companyId' : CompanyId,
}
export interface RegisterRequest {
  'password' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface StatusCount { 'status' : OrderStatus, 'count' : bigint }
export type Timestamp = bigint;
export type UserId = bigint;
export interface UserPublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  'acceptOrder' : ActorMethod<[string, bigint], AssignOrderResult>,
  'adminCreateCompany' : ActorMethod<
    [string, CompanyInput],
    { 'ok' : CompanyPublic } |
      { 'err' : string }
  >,
  'adminCreateOffer' : ActorMethod<
    [string, OfferInput],
    { 'ok' : OfferPublic } |
      { 'err' : string }
  >,
  'adminCreateProduct' : ActorMethod<
    [string, ProductInput],
    { 'ok' : ProductPublic } |
      { 'err' : string }
  >,
  'adminDeleteCompany' : ActorMethod<
    [string, CompanyId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteOffer' : ActorMethod<
    [string, OfferId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteProduct' : ActorMethod<
    [string, ProductId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminLoginCall' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSendBroadcastNotification' : ActorMethod<
    [string, string, string, BroadcastSegment],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminSetPaymentMethodEnabled' : ActorMethod<
    [string, PaymentMethod, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateCompany' : ActorMethod<
    [string, CompanyId, CompanyInput],
    { 'ok' : CompanyPublic } |
      { 'err' : string }
  >,
  'adminUpdateOffer' : ActorMethod<
    [string, OfferId, OfferInput],
    { 'ok' : OfferPublic } |
      { 'err' : string }
  >,
  'adminUpdateProduct' : ActorMethod<
    [string, ProductId, ProductInput],
    { 'ok' : ProductPublic } |
      { 'err' : string }
  >,
  'cancelOrder' : ActorMethod<
    [string, bigint],
    { 'ok' : OrderPublic } |
      { 'err' : string }
  >,
  'confirmDelivery' : ActorMethod<
    [string, bigint, number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmPickup' : ActorMethod<
    [string, bigint, number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'courierLogin' : ActorMethod<[string, string], CourierLoginResult>,
  'createNotification' : ActorMethod<
    [bigint, NotificationType, [] | [bigint], string, string],
    undefined
  >,
  'createOrder' : ActorMethod<
    [string, CreateOrderRequest],
    { 'ok' : OrderPublic } |
      { 'err' : string }
  >,
  'getActiveCompanies' : ActorMethod<[], Array<CompanyPublic>>,
  'getActiveOffers' : ActorMethod<[], Array<OfferPublic>>,
  'getActiveProducts' : ActorMethod<[], Array<ProductPublic>>,
  'getAllOrdersAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : string }
  >,
  'getAllPaymentMethodSettings' : ActorMethod<
    [],
    Array<PaymentMethodSettingPublic>
  >,
  'getAllUsersAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<UserPublic> } |
      { 'err' : string }
  >,
  'getCompany' : ActorMethod<[CompanyId], [] | [CompanyPublic]>,
  'getCourierLocation' : ActorMethod<
    [bigint],
    [] | [
      {
        'lat' : number,
        'lng' : number,
        'orderId' : bigint,
        'timestamp' : bigint,
        'courierId' : bigint,
      }
    ]
  >,
  'getCourierProfile' : ActorMethod<[string], [] | [CourierPublic]>,
  'getCourierStats' : ActorMethod<[string], CourierStats>,
  'getDashboardStats' : ActorMethod<
    [string],
    { 'ok' : DashboardStats } |
      { 'err' : string }
  >,
  'getEnabledPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getMyCourierOrders' : ActorMethod<[string], Array<OrderPublic>>,
  'getMyNotifications' : ActorMethod<[string], Array<NotificationPublic>>,
  'getMyOrders' : ActorMethod<
    [string],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<[string], [] | [UserPublic]>,
  'getOffer' : ActorMethod<[OfferId], [] | [OfferPublic]>,
  'getOrder' : ActorMethod<[string, bigint], [] | [OrderPublic]>,
  'getOrderPayments' : ActorMethod<[string, bigint], Array<PaymentPublic>>,
  'getOrdersByPaymentMethodAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<PaymentMethodCount> } |
      { 'err' : string }
  >,
  'getOrdersByStatusAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<StatusCount> } |
      { 'err' : string }
  >,
  'getOrdersLast7DaysAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<DailyOrderCount> } |
      { 'err' : string }
  >,
  'getPaymentStatus' : ActorMethod<[string, bigint], [] | [PaymentPublic]>,
  'getPendingOrdersForCourier' : ActorMethod<[string], Array<OrderPublic>>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductPublic]>,
  'getTotalOrdersAdmin' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getTotalUsersAdmin' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getUnreadNotificationCount' : ActorMethod<[string], bigint>,
  'getUserByIdAdmin' : ActorMethod<
    [string, bigint],
    { 'ok' : [] | [UserPublic] } |
      { 'err' : string }
  >,
  'initiatePayment' : ActorMethod<
    [string, bigint, PaymentMethod, [] | [string]],
    { 'ok' : PaymentPublic } |
      { 'err' : string }
  >,
  'isAdmin' : ActorMethod<[string], boolean>,
  'listCompanies' : ActorMethod<[boolean], Array<CompanyPublic>>,
  'listOffers' : ActorMethod<[boolean], Array<OfferPublic>>,
  'listProducts' : ActorMethod<[boolean], Array<ProductPublic>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], undefined>,
  'markAllNotificationsRead' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'register' : ActorMethod<
    [RegisterRequest],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'registerCourier' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : CourierPublic } |
      { 'err' : string }
  >,
  'searchOrders' : ActorMethod<
    [string, OrderSearchFilter],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : string }
  >,
  'searchUsersAdmin' : ActorMethod<
    [string, string],
    { 'ok' : Array<UserPublic> } |
      { 'err' : string }
  >,
  'setUserActiveAdmin' : ActorMethod<
    [string, bigint, boolean],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'updateCourierLocation' : ActorMethod<
    [string, bigint, number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [string, bigint, OrderStatus],
    { 'ok' : OrderPublic } |
      { 'err' : string }
  >,
  'updatePaymentStatus' : ActorMethod<
    [bigint, PaymentStatus, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];